Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/ClassVars: 
  Enabled: false
AllCops:
 TargetRubyVersion: 2.6.3 
 NewCops: enable

